name: CI

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Install TruffleHog
      run: pip install trufflehog

    - name: run trufflehog
      run: trufflehog --json . > trufflehog-json
            
    - name: upload artefact
      uses: actions/upload-artifact@master
      with:
        name: trufflehog
        path: ${{ github.workspace }}/trufflehog-json
    
#    - name: Send truffleHog to Slack
 #     run: python output_to_slack.py --webhook ${{ secrets.SLACK_WEBHOOK }} --trufflehog
